Dangelo feature
JuanLPalacios/apprun-leaflet pull request #7
Opened 2022-10-10 00:42 UTC by Dangelo-JAN

# I create the AppRun LeafLet style

In this milestone I:

- Use the Markdown component to the documentation
- Add the style to the initial LeafLet's wrapper version

2022-10-10 21:42 UTC, JuanLPalacios requested changes
hey @Dangelo-JAN, it looks good in general but some changes are still needed, please check the comments for more details

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +
- [x] Remember to please add an acknowledgment about the leaflet getting started tutorial and that we are following the same steps adapted to Apprun-leaflet

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +            and dealing with events.
- [x] This refers to Apprun-leaflet, not Leaflet please correct it as it causes poor SEO

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +            Before writing any code for the map, you need to do the following preparation steps on your page:
- [x] Please add the npm and CSS setup in the readme to this section to avoid confusion from readers

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +              ~~~
- [x] Please move this to later on in n the section dealing with events as it is not used at this point

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +                    eventHandlers={{ click: (e) => {this.setState({position: e.latlng})}  }}>
- [x] Please move this to later on in n the section dealing with events as well

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +            Note that the center call also returns the map object — most Leaflet methods act like this when they don’t return an explicit value, which allows convenient jQuery-like method chaining.
- [x] Please remove this as it is not present in our wrapper

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +                  eventHandlers={{ click: (e) => {this.setState({position: e.latlng})}  }}>
- [x] Please move this to later on in n the section dealing with events as well

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +            ~~~
- [x] Please add a const definition for mapPosition

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +            </Popup>
- [x] Please remove the event handler and conditional popup message as it is explained later on in n the section dealing with events

2022-10-10 21:42 UTC, JuanLPalacios commented on demo/home.tsx
> +        <p>Here we use openOn instead of addTo because it handles automatic closing of a previously opened popup when opening a new one which is good for usability.</p>
- [x] Please replace this with a mention that popups in the map component start open by default

2022-10-10 22:15 UTC, Dangelo-JAN commented on demo/home.tsx
> +
done

2022-10-10 22:17 UTC, Dangelo-JAN commented on demo/home.tsx
> +            and dealing with events.
Done

2022-10-10 22:21 UTC, Dangelo-JAN commented on demo/home.tsx
> +            Before writing any code for the map, you need to do the following preparation steps on your page:
Done

2022-10-10 22:28 UTC, Dangelo-JAN commented on demo/home.tsx
> +              ~~~
Done

2022-10-10 22:36 UTC, Dangelo-JAN commented on demo/home.tsx
> +                    eventHandlers={{ click: (e) => {this.setState({position: e.latlng})}  }}>
Done

2022-10-10 22:36 UTC, Dangelo-JAN commented on demo/home.tsx
> +            Note that the center call also returns the map object — most Leaflet methods act like this when they don’t return an explicit value, which allows convenient jQuery-like method chaining.
Done

2022-10-10 22:36 UTC, Dangelo-JAN commented on demo/home.tsx
> +                  eventHandlers={{ click: (e) => {this.setState({position: e.latlng})}  }}>
Done

2022-10-10 22:41 UTC, Dangelo-JAN commented on demo/home.tsx
> +            ~~~
Done

2022-10-10 22:43 UTC, Dangelo-JAN commented on demo/home.tsx
> +            </Popup>
Done

2022-10-10 22:45 UTC, Dangelo-JAN commented on demo/home.tsx
> +        <p>Here we use openOn instead of addTo because it handles automatic closing of a previously opened popup when opening a new one which is good for usability.</p>
Done

2022-10-11 21:35 UTC, JuanLPalacios approved these changes
@Dangelo-JAN this seems fine to me, great work!👏👏👏

2022-10-11 21:54 UTC, merged